RFmxBT Scrapigen Update to 24.0
ni/grpc-device pull request #1026
Opened 2023-12-11 05:40 UTC by alenkani

### What does this Pull Request accomplish?

Updates niRFmxInstr in grpc-device-scrapigen to 24.0
Updated manually niRFmxBt_exclude.h file to skip property specific Set/Get APIs as per the design.

### Why should this Pull Request be merged?
Updated to match the upcoming release of niRFmxBt 24.0.0
There are Lot of apis rearranged because of Code clean Up 

### What testing has been done?
Manually inspected generated files.
Copied files from grpc-device-scrapigen/out/rfmxBT/export/ to grpc-device/source/codegen/metadata/nirfmxBT/ and built grpc-device successfully.
Manually inspected nirfmxbt.proto file.

2023-12-11 17:41 UTC, reckenro commented on generated/nirfmxbluetooth/nirfmxbluetooth.proto
> +  int32 measurement_status = 2;
Commented in [the scrapigen PR](https://github.com/ni/grpc-device-scrapigen/pull/204) so hopefully we can avoid this binary-breaking change.

2023-12-11 17:41 UTC, reckenro requested changes
Waiting to see if we can avoid the binary-breaking change.

2023-12-11 20:24 UTC, maxxboehme commented
@alenkani are you wanting to have this PR included in the 2.4 release of grpc-device or can it wait for the next. We are currently in the process of releasing grpc-device for 2.4 today.

2023-12-12 15:53 UTC, reckenro approved these changes

2023-12-12 15:59 UTC, reckenro commented
Can you update the PR description to not mention Instr since you aren't changing it?

2023-12-12 20:51 UTC, astarche approved these changes

2023-12-12 23:28 UTC, merged