Create Security Policy for grpc-device
ni/grpc-device pull request #1031
Opened 2023-12-19 21:33 UTC by shastriUF

### What does this Pull Request accomplish?

Publishes a security policy - leveraged existing NI policy published at https://nilrt-docs.ni.com/policies/security_response_policy.html for the content for grpc-device's policy. 

### Why should this Pull Request be merged?
This is general good practice, and will be enforced via internal NI processes soon. 

### What testing has been done?
N/A

2023-12-19 22:10 UTC, astarche approved these changes

2023-12-20 17:19 UTC, reckenro commented on SECURITY.md
> +NI is committed to resolving major security vulnerabilities discovered grpc-device.
```suggestion
NI is committed to resolving major security vulnerabilities discovered in grpc-device.
```

2023-12-20 17:21 UTC, reckenro commented on SECURITY.md
> +If you are interested in reporting a security issue in an NI product other than NI LinuxRT, reference the company security page [here](https://ni.com/security).
```suggestion
If you are interested in reporting a security issue in an NI product other than grpc-device, reference the company security page [here](https://ni.com/security).
```

2024-01-04 18:25 UTC, bkeryan requested changes

2024-01-04 18:25 UTC, bkeryan commented on SECURITY.md
Please see the security policy that @kyle-ni added to the GitHub repo template: https://github.com/ni/github-repo-template/blob/main/SECURITY.md

2024-01-04 20:11 UTC, bkeryan approved these changes

2024-01-04 22:00 UTC, maxxboehme approved these changes

2024-01-04 22:05 UTC, merged