Users/christag/ni/debug symbols with release
ni/grpc-device pull request #1040
Opened 2024-02-07 16:03 UTC by christag-ni

### What does this Pull Request accomplish?

Adds a new asset `ni-grpc-device-server-windows-x64-debug-symbols` to all releases.
### Why should this Pull Request be merged?

This is helpful for debugging release versions .

### What testing has been done?

No testing

2024-02-07 16:24 UTC, bkeryan requested changes

2024-02-07 16:24 UTC, bkeryan commented on .github/workflows/build_cmake.yml
> +          build/Debug/ni_grpc_device_server.pdb
This looks like symbols for a Debug build, not a RelWithDebInfo build. I would expect the RelWithDebInfo symbols to be in build/Release or build/RelWithDebInfo.

2024-02-07 16:38 UTC, bkeryan commented on .github/workflows/build_cmake.yml
> +          build/Debug/ni_grpc_device_server.pdb
If the files are in build/RelWithDebInfo, don't you also need to update the other steps to use that directory?

```
    - name: Upload Windows Server Binaries Artifact
      uses: actions/upload-artifact@v2
      if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/releases')) && (runner.os == 'Windows') }}
      with:
        name: ni-grpc-device-server-windows-x64
        path: |
          build/Release/ni_grpc_device_server.exe
          build/Release/server_config.json
          build/Release/server_capabilities.json
        retention-days: 5
```

2024-02-07 17:30 UTC, astarche approved these changes

2024-02-07 22:05 UTC, reckenro approved these changes

2024-02-07 22:36 UTC, bkeryan approved these changes

2024-02-14 19:03 UTC, merged

2024-02-14 19:06 UTC, bkeryan commented
@christag-ni Sorry I didn't notice this before, but in the future, please edit your PR titles so they don't say "Users/..."

2024-02-14 19:08 UTC, christag-ni commented
@bkeryan Of course, it must've been a typing error when creating this PR. My apologies.