Close sideband socket gracefully when closing the grpc server
ni/grpc-device pull request #1132
Opened 2024-11-28 04:59 UTC by amehra-ni

### What does this Pull Request accomplish?

We need to close the sideband socket when grpc-server shuts down gracefully. Hence, this PR adds support for it.

### Why should this Pull Request be merged?

To the sideband codebase, we will pass a boolean variable by reference to the sideband function, which will act as a trigger for closing the socket. The sideband socket will be closed whenever this boolean is set to true.

### What testing has been done?

When closing the grpc-server, the sideband socket also closes.
![34](https://github.com/user-attachments/assets/7d385414-eac2-4f40-b7e7-511d043b7cf8)
(Will we update the message shown later on in the sideband repo)

2024-12-05 17:27 UTC, maxxboehme requested changes

2024-12-05 17:35 UTC, amehra-ni commented on source/server/sideband_manager.cpp
> +}
I have updated it to close the thread if it is already running.

2024-12-05 17:36 UTC, amehra-ni commented on source/server/sideband_manager.cpp
> +}
I have updated the code so that when we start the thread, we ensure the variable is set to false.

2024-12-16 19:25 UTC, christag-ni commented
We are planning to create a release branch on the 18th, and your PR will need to be completed before then for the changes to be in effect. Do you want these changes included in this release?

2024-12-18 16:22 UTC, christag-ni commented
I'll be creating the release branch at 11:30 CST.

2025-01-02 19:20 UTC, maxxboehme approved these changes

2025-01-21 06:09 UTC, closed without merging

2025-01-21 06:09 UTC, doshirohan commented
After pulling in changes submitted to grpc-sideband to gracefully shutdown the sideband server, streaming using sideband mechanism doesn't work in grpc-device. Abandoning this review request as we are not planning to work on this any time soon.