Time functions
ni/grpc-device pull request #186
Opened 2021-05-07 17:58 UTC by ppease

### What does this Pull Request accomplish?

Add several methods related to time functionality for the time reference test panel for NI-Sync.
Methods Added:
```
SetTime
GetTime
SetTimeReferenceFreeRunning
SetTimeReferenceGPS
SetTimeReferenceIRIG
SetTimeReferencePPS
SetTimeReference1588OrdinaryClock
SetTimeReference8021AS
```

### Why should this Pull Request be merged?

Adding methods need for the time reference test panel for NI-Sync.

### What testing has been done?

System tests were added for all new methods, and they are passing on a system with a 6683.  There is one test that is still failing that I am going to submit for now, and I'm tracking it with a bug.

2021-05-07 18:00 UTC, ppease commented on source/codegen/proto_helpers.py
> +  if 'ViUInt16' in type:
I guess I was the first one to use ViUInt16 in our API.  I looked through the documentation for the proto standard, and it looks like there isn't a representation for 16 bit numbers.  Above this we are already turning ViInt8 into a 32 bit integer so I am doing the same here for the 16 bit type.

2021-05-10 14:18 UTC, zhindes requested changes

2021-05-11 06:48 UTC, tkrebes commented on source/tests/system/nisync_driver_api_tests.cpp
> +TEST_F(NiSyncDriverApiTest, SetTimeWithValidTimeSource_ReturnsSuccess)
The updates I'm making to the NI-Sync system tests in #192 should make that  easier to do.

2021-05-11 13:37 UTC, zhindes commented on source/tests/system/nisync_driver_api_tests.cpp
> +TEST_F(NiSyncDriverApiTest, SetTimeWithValidTimeSource_ReturnsSuccess)
Yeah, I just saw that. Awesome!

2021-05-12 15:20 UTC, ppease commented on source/tests/system/nisync_driver_api_tests.cpp
> +TEST_F(NiSyncDriverApiTest, SetTimeWithValidTimeSource_ReturnsSuccess)
For now I am disabling these tests.  I am creating a separate task under the same user story to address splitting up the tests based on model and removing the DISABLED_ from the tests.

2021-05-12 15:27 UTC, zhindes approved these changes

2021-05-12 15:48 UTC, tkrebes approved these changes

2021-05-12 16:44 UTC, jonlugoatx approved these changes

2021-05-12 17:15 UTC, reckenro approved these changes

2021-05-12 17:16 UTC, merged