Update CMakeLists.txt
ni/grpc-device pull request #893
Opened 2023-03-27 19:36 UTC by christag-ni

### What does this Pull Request accomplish?

Bumps the version in CMake file
### Why should this Pull Request be merged?

To accurately reflect the version grpc-device is in
### What testing has been done?

No testing

2023-03-28 14:48 UTC, reckenro requested changes
Change looks fine. 

I thought about this more after we discussed it and I don't think we should submit anything into main until we've bumped the exports from main to be 2.2 (in AzDo). This is mainly so if someone gets the latest 2.1 exports they'll get the finals from the release branch.

2023-03-28 16:01 UTC, christag-ni commented
> Change looks fine.
> 
> I thought about this more after we discussed it and I don't think we should submit anything into main until we've bumped the exports from main to be 2.2 (in AzDo). This is mainly so if someone gets the latest 2.1 exports they'll get the finals from the release branch.

Should I then create a PR for the ni-central changes, and once those changes are submitted, we submit this change in grpc-device?

2023-03-28 16:11 UTC, reckenro commented
> Should I then create a PR for the ni-central changes, and once those changes are submitted, we submit this change in grpc-device?

Yes, sorry for switching these around. But yes, I think we're good to make that AzDo change now that Wes's cherry-pick went in and we're firm that we're not going to make further changes to the releases/2.1 branch.

2023-03-29 15:41 UTC, reckenro approved these changes

2023-03-29 16:32 UTC, merged